<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graphgrammar" nsURI="org.wbsilva.bence.graphgrammar" nsPrefix="org.wbsilva.bence.graphgrammar">
  <eClassifiers xsi:type="ecore:EClass" name="Grammar">
    <eOperations name="derives" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="prev" eType="#//Graph"/>
      <eParameters name="next" eType="#//Graph"/>
      <eParameters name="vertex" eType="#//Vertex"/>
      <eParameters name="rhs" eType="#//Graph"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alphabet" ordered="false"
        upperBound="-1" eType="#//Symbol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terminals" ordered="false"
        upperBound="-1" eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nonterminals" ordered="false"
        upperBound="-1" eType="#//Symbol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" ordered="false"
        upperBound="-1" eType="#//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" eType="#//Symbol"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eOperations name="embed" ordered="false" upperBound="-1" eType="#//Edge">
      <eParameters name="graph" eType="#//Graph"/>
      <eParameters name="edges" ordered="false" upperBound="-1" eType="#//Edge"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//Symbol"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//Graph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embedding" upperBound="-1"
        eType="#//VertexLabelPairToSymbolMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pac" ordered="false" upperBound="-1"
        eType="#//Vertex"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VertexLabelPair">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertex" eType="#//Vertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeLabel" eType="#//Symbol"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VertexLabelPairToSymbolMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//VertexLabelPair"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        upperBound="-1" eType="#//Symbol" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivationStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertex" eType="#//Vertex"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Derivation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//DerivationStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph">
    <eOperations name="neighbors" ordered="false" upperBound="-1" eType="#//Vertex">
      <eParameters name="vertices" ordered="false" upperBound="-1" eType="#//Vertex"/>
    </eOperations>
    <eOperations name="isomorphicTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="#//Graph"/>
    </eOperations>
    <eOperations name="inEdges" ordered="false" upperBound="-1" eType="#//Edge">
      <eParameters name="vertex" eType="#//Vertex"/>
    </eOperations>
    <eOperations name="outEdges" ordered="false" upperBound="-1" eType="#//Edge">
      <eParameters name="vertex" eType="#//Vertex"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertices" ordered="false"
        upperBound="-1" eType="#//Vertex" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" ordered="false"
        upperBound="-1" eType="#//Edge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vertex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Symbol"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ZoneVertex" eSuperTypes="#//Vertex">
    <eOperations name="equivalates" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" eType="#//ZoneVertex"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertices" upperBound="-1"
        eType="#//Vertex" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eOperations name="compareTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="other" eType="#//Edge"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//Vertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//Vertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Symbol"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
