<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="star2wheel" nsURI="platform:/plugin/org.wbsilva.bx.star2wheel/model/Star2wheel.ecore"
    nsPrefix="org.wbsilva.bx.star2wheel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.wbsilva.bx"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Node2Node" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.wbsilva.mm.graph/model/Graph.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.wbsilva.mm.graph/model/Graph.ecore#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="G2G" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.wbsilva.mm.graph/model/Graph.ecore#//G"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.wbsilva.mm.graph/model/Graph.ecore#//G"/>
  </eClassifiers>
  <eSubpackages name="Rules" nsURI="platform:/plugin/org.wbsilva.bx.star2wheel/model/Star2wheel.ecore#//Rules"
      nsPrefix="Rules">
    <eClassifiers xsi:type="ecore:EClass" name="qn2qn" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="sn2sn" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="g2g" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="tn2tn_fin" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="qn2qn_fin" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="dn2dn" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="tn2tn" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
  </eSubpackages>
</ecore:EPackage>
